### ISSUE TITLE
Questions about chproxy setting https

### ISSUE THREAD

**Issue by zcw5116** [ContentSquare/chproxy#120]
When I configure the listen_addr of http to 9090：

_server:
  http:
      listen_addr: ":9090"
      allowed_networks: ["192.168.0.0/16","10.10.10.0/24"]
  https:
    listen_addr: ":443"
    autocert:
      cache_dir: "certs_dir"_

the startup error is reported as follows:
`
FATAL: 2021/06/04 08:25:54 main.go:147: `letsencrypt` specification requires http server to listen on :80 port to satisfy http-01 challenge. Otherwise, certificates will be impossible to generate
`

When the listen_addr of http is modified to 80, the startup is normal.
_server:
  http:
      listen_addr: ":80"
      allowed_networks: ["192.168.0.0/16","10.10.10.0/24"]
  https:
    listen_addr: ":443"
    autocert:
      cache_dir: "certs_dir"_

Two questions：
（1）、Why set the port of the http address to 80?
（2）、When I configure https, how to use jdbc to access clickhouse?

Thank You.

**Comment by vfoucault** [comment]
AFAIK this is a normal behavior when using let's encrypt. LE will check for a challenge on http/80 in order to issue the certificate.

In order to use a ssl connection in with JDBC, configure it to have ssl configured with the relevant ssl settings.

check https://github.com/ClickHouse/clickhouse-jdbc/issues/95 for a good start.

**Comment by gontarzpawel** [comment]
Hello @zcw5116, do you still need some help?

**Comment by zcw5116** [comment]
> Hello @zcw5116, do you still need some help?

Now it's Ok, Thank You very much.
