### ISSUE TITLE
The time zone in the chproxy log is incorrect, how to solve it

### ISSUE THREAD

**Issue by jim-zong** [ContentSquare/chproxy#122]
The time zone in the chproxy log is incorrect, how to solve it？

**Comment by vfoucault** [comment]
Without further info I would say that the time zone is incorrect on the machine where you run chproxy.

**Comment by sszc** [comment]
My time zone is also wrong, I checked the machine's time zone is correct.

$ date -R
Mon, 06 Sep 2021 09:11:12 +0800

**Comment by 2416210017** [comment]
Yes, I also found it. How can I solve it?
`INFO: 2022/01/21 09:02:37 main.go:53: Loading config "/app/chproxy/config/config.yml": successful
INFO: 2022/01/21 09:02:37 main.go:152: Serving http on ":9090`

`#  date "+%Y-%m-%d %H:%M:%S"
2022-01-21 17:08:09
`

**Comment by ryze124** [comment]
Me too. How to solve it ?

**Comment by bigdata-spec** [comment]
@1241407808 @2416210017 @sszc @jim-zong @vfoucault  Hello,How to solve it ?

**Comment by mga-chka** [comment]
I'm closing since the following issue is a duplicated https://github.com/ContentSquare/chproxy/issues/236
Currently the logs are written in UTC, there is no way to use the local timezone. If you have time, feel free to modify the code to allow UTC or local timezone in the logs (it shouldn't be a big PR)
