### ISSUE TITLE
protocol between application and chproxy

### ISSUE THREAD

**Issue by LatchShun** [ContentSquare/chproxy#130]
What's the protocol between application and chproxy?  Is it http/jhttps?

if it is http, i'm confused of the description part.

```
What about chproxy performance?
A single chproxy instance easily proxies 1Gbps of compressed INSERT data while using less than 20% of a single CPU core in our production setup.
```

How to post 1Gbps between application and chproxy? And how many columns when you test?

**Comment by mga-chka** [comment]
Hi, the protocol is HTTP/HTTPS.

The HTTP protocol should not prevent you to achieve a 1Gbps throughput if you send enough data per call so that the http overhead is negligible.
Since the tests were done by the previous owner of CHProxy I can't tel you how they were done. But the number of columns shouldn't have an impact

Can you be more precise on the part that confuses you?

**Comment by mga-chka** [comment]
Since there are no more answer/question from @LatchShun , I'll close this issue
