### ISSUE TITLE
[BUG] Chproxy adds 30s max_execution_time to users by default

### ISSUE THREAD

**Issue by roimor** [ContentSquare/chproxy#182]
**Describe the bug**
Chproxy adds 30s max_execution_time to users by default in contrast to the docs. ("By default there is no limit on the query duration." -  https://github.com/ContentSquare/chproxy/blob/f4a34c3d09120578979abba15c23f683c2345951/docs/content/en/configuration/default.md?plain=1#L228)

**To Reproduce**
In the config dont set any max_execution_time , observe the logs of chproxy and see that max_execution_time is added to the user with 30s max_execution_time

**Environment information**
Docker container Chproxy version 1.6.0

**Comment by mga-chka** [comment]
looks like the bug was introduced 3 months ago by the PR https://github.com/ContentSquare/chproxy/pull/146

We will see if we can fix the behavior or just modify the doc.

**Comment by mga-chka** [comment]
cf the activity, the doc has just been modified according to this new behavior:
https://github.com/ContentSquare/chproxy/pull/186
So I'll close this issue

**Comment by roimor** [comment]
@mga-chka  why did you go with updating the doc? don't you agree that this is a bug? 
PLEASE let me know if this fix by my team member makes sense:
https://github.com/ContentSquare/chproxy/commit/d0956033f6cab8f0a6673c6c1eab687100e95bac

This is a more elegant way to address this, so please consider it

**Comment by roimor** [comment]
i would also ask you to re-open this issue until you guys can go through this PR and approve it: https://github.com/ContentSquare/chproxy/pull/187

**Comment by mga-chka** [comment]
Hi, 
As requested I've reopened the issue.
In the end we went with modifying the doc because:
- the max_execution_time is linked to the way CHProxy handles concurrent queries (since https://github.com/ContentSquare/chproxy/pull/146 that enforced the default value to 30 sec) and putting an unlimited value will break the logic
- the hidden regression you spotted is present on all version released for  the last 3 months

So we thought updating the doc now might be better than waiting for a clean fix (linked to the way concurrent queries handling works ) for maybe 1-2 more months.

**Comment by roimor** [comment]
So @mga-chka let me see that I got you correctly , this PR is not clean enough? https://github.com/ContentSquare/chproxy/pull/187

**Comment by mga-chka** [comment]
Yes it's not enough because there will be a side effect on the way chproxy manages concurrent queries. I'm not sure but with a value at 0 it will either not work or create a memory leak.
It's because when fixing the way concurrent queries worked (there was a huge bug in the previous implantation making it useless) we wrongly used the max duration time property to avoid adding a new config variable difficult to understand. We though that no one was using an unlimited duration and if it was the case, the duration was likely the same as CH default duration (but thinking of it, I'm not sure CH has a default duration and the 30 sec is specific to contentsquare's setup). A quick fix could be to increase the default value (if were not talking about queries taking jours). Would it be ok for you?

FYI, the idea of this concurrent query feature is if the same query is run while the first one is still processed and therefore not cached yet, chproxy will wait a bit for the first one to finish  before executing the second query

**Comment by roimor** [comment]
@mga-chka i think increasing the default to 1 minute is reasonable yeah

**Comment by mga-chka** [comment]
the fix is on its way. I decided to use 2 minutes by default, which should be large enough for most CHProxy's users.
Once the PR (https://github.com/ContentSquare/chproxy/pull/195) is merged, I'll close your PR (https://github.com/ContentSquare/chproxy/pull/187)

**Comment by mga-chka** [comment]
The code is merged and I closed your PR, a new version of CHProxy with the fix was released (v1.16.3).
