### ISSUE TITLE
Header Content-length present only when using cache

### ISSUE THREAD

**Issue by Ravojay** [ContentSquare/chproxy#223]
Hi all,
Seems that the Content-length is set only when using cache and is calculated from the file, any explanation why not set it to all responses? Also, is there an easy way of getting the size of the response from clickhouse server without modifying a lot of the dependency packages?

**Comment by mga-chka** [comment]
Hi,

The short answer is no because of performance reasons.

Clickhouse doesn't give the content-length in the HTTP headers when chproxy queries it.
For example, here is the list of headers given by clickhouse when I do a query using http
```bash
curl -i 'http://localhost:8123/?query=SELECT%20*%20FROM%20system.numbers%20limit%2010'

HTTP/1.1 200 OK
Date: Tue, 06 Sep 2022 11:50:11 GMT
Connection: Keep-Alive
Content-Type: text/tab-separated-values; charset=UTF-8
X-ClickHouse-Server-Display-Name: christophe-laptop
Transfer-Encoding: chunked
X-ClickHouse-Query-Id: 078c5d39-c329-4918-8329-b259f35799b1
X-ClickHouse-Format: TabSeparated
X-ClickHouse-Timezone: Europe/Paris
Keep-Alive: timeout=3
X-ClickHouse-Summary: {"read_rows":"10","read_bytes":"80","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}

0
1
2
3
4
5
6
7
8
9
```
ClickHouse doesn't send this information because it doesn't have it when it starts streaming the result of the query trough HTTP  (nb: I'm not 100% sure about that but it seems logical). 
When the cache is activated, chproxy first puts the result of the clickhouse query in a temporary file then, once the result is fully received and put in this file, it sends it the user & caches it. Since the full result is known by chproxy before sending it, it can send a content-length http header.
When the cache is not activated, chproxy just passes the data from clickhouse to the user in a streaming way. We don't want to add the extra step to store the full result in a temporary a file just for the content-length because it impacts a lot the processing speed of the SQL queries.

**Comment by mga-chka** [comment]
I'm closing the PR.
FYI since v1.17.1 there is a trick to do what you want: You can create a filesystem cache and use the max_payload_size field to say to you don't want to cache results bigger than 1 bytes (so all the results). Doing so will force chproxy to first put all the result in a file and it will give you the result with a Content-length header.
