### ISSUE TITLE
[BUG] failed to reach redis: got 4 elements in cluster

### ISSUE THREAD

**Issue by 313177606** [ContentSquare/chproxy#255]
use redis cluster  config address [ "172.18.239.134:6379","172.18.239.133:6379", "172.18.239.132:6379"] 
 main.go:55: error while applying config: failed to reach redis: got 4 elements in cluster info address, expected 2 or 3
 
![image](https://user-images.githubusercontent.com/8287476/198775554-389efd7e-f3a1-40ed-9d79-133adf2b2231.png)

**Comment by mga-chka** [comment]
are you sure the IPs are part of the same redis cluster?

**Comment by mga-chka** [comment]
FYI we're relying on the go-redis lib to connect with redis and someone got the same issue as you.
It seems that the lib we're using is not compatible with redis 7 in cluster mode. Is it the version of redis you're using?
I let you read the thread for more details but the issue is on the current version of go-redis (8.x). The new version (9) should solve the issue but it's still under development https://github.com/go-redis/redis/issues/2085

**Comment by 313177606** [comment]
hi bro ,, checked  my redis  version is  7.0    thkx

**Comment by mga-chka** [comment]
FYI the new version of go-redis that should fix the problem is available
When we use this version (soon) and I'll close this issue.
