### ISSUE TITLE
[QUESTION] Set timeout in case redis is down

### ISSUE THREAD

**Issue by inakisoriamrf** [ContentSquare/chproxy#259]
**Which feature your question relates to?**
caching with Redis

**Question details**
Is there any variable to lower the timeout with Redis in case Redis is down?
**Additional context/motivations**
Being able to tweak this value allows us to have a single redis instance and connect directly to CH in case it's down (reboots, node changes...) without needing to set up a full redis cluster

**Comment by mga-chka** [comment]
currently no.
If you can, you can do a PR to add the ability to change MaxRetries, MinRetryBackoff & MaxRetryBackoff in the redis client using values in the configuration.
This change should not be too difficult since the function creating the redis client takes the configuration  in argument
https://github.com/ContentSquare/chproxy/blob/master/clients/redis.go#L17
