### ISSUE TITLE
[QUESTION] `chproxy` in a follower - leader setup

### ISSUE THREAD

**Issue by vorillaz** [ContentSquare/chproxy#261]
**Which feature your question relates to?**
Load balancing across two ClickHouse instances in a leader / follower scenario. 

**Question details**
Hi there,
Thanks a ton for this amazing project. Currently, we are evaluating `chproxy` as a way to provide a highly available setup with minimal effort and maximum performance. Our setup would be quite simple and common with two single node ClickHouse instances sitting behind `chproxy`, the biggest instance is serving as a leader, the second one is used a follower. 
Upon inserting, we digest data in both instances, `chproxy` would distribute the inserts. Upon selecting / retrieving data we would also use the leader machine. If, for some reason, the leader is down due to maintenance or hardware errors and the instance's health check would pinpoint `chproxy` to use the follower data warehouse for reading and writing.

We are not looking for any sort of automated data syncing, just wondering if it would be possible to achieve a setup through the chproxy configuration options.

**Additional context/motivations**
According to different resources across the web, ClickHouse can actually work great with a single node instance, creating a cluster, taking sharding into consideration or using additioanl resources would require extra effort which might not be trivial for a small team of engineers. Using chproxy with a follower/leader setup allows us to provide a fault tolerance infrastructure where we can take down or spin off additional Clickhouse servers when something's not working or when we need to do some maintenance tasks.

Thanks in advance.

**Comment by mga-chka** [comment]
short answer:
you should use a clickhouse cluster and chproxy won't be able in the setup you're planning to do.

long answer:
Yes a clickhouse in cluster mode is more painful to maintain than clickhouse in stand-alone. We've been maintaining a dozen of clusters at contentsquare since 2018 so we have some knowledge on that part.
But when we created our first cluster in production in 2018 (with multiple shards & replicas), it didn't require that much maintenance (like a few hours per month on average) and there were only 2-3 people who were able to troubleshoot it during the first 2 years.
Moreover, the last versions of ClickHouse include a service, clickhouse-keeper (in the clickhouse binary so it's transparent for you), that allows you to avoid zookeeper in cluster mode. So, you should use clickhouse cluster with 1 shard - 2 replicas. It will just require a few hours to find the right config and will require less maintenance than doing yourself an active-passive configuration (and dealing manually the data discrepancies that will happen or dealing with the discrepancies in the sql schemas or many things).
On top of that you can add chproxy so that if one of the 2 shards is down the system will work (and you'll benefit from other chproxy's feature like query caching).

Regarding your question, I'm not sure I follow exactly what you have in mind so I'll rephrase and answer:
- chproxy will not be able to insert the data in both the leader and the follower. The use case of chproxy is more to spread the load btw the leader and the follower assuming they're replicas of the same shard then clickhouse will distribute the data among the 2 replicas.
- regarding the ability to query only the leader or the follower if the leader is dead, it's possible only if when the leader is up the follower is down. Indeed, chproxy maintains an healthcheck of every server in the cluster and only reaches the servers that are alive. 

I hope it answers your question.

**Comment by mga-chka** [comment]
since there are no more msg after my answer, I assume the question was answer and therefore I'm closing it.
If it's not the case, feel free to reopen the issue
