### ISSUE TITLE
Keys are stored with _tmp and always gives Cache Miss when used in Multi Node Redis Cluster

### ISSUE THREAD

**Issue by SouradipPoddar** [ContentSquare/chproxy#319]
We have a setup of a redis cluster with 3 master and 3 replica nodes. We are using CHProxy as a caching layer for our application. Previously we had used the file system type of chproxy. Now we are moving to redis. We can see that all keys are being stored as _tmp. When hitting the same query again, CHProxy gives a cache miss and inserts another record with _tmp suffix.

![temp_prefix_snap](https://user-images.githubusercontent.com/49103513/223073654-2e28cbad-3da7-4290-b60a-bccae07d6b90.png)

**Comment by SouradipPoddar** [comment]
Fix is part of this PR. #320 
Awaiting review.

**Comment by mga-chka** [comment]
can you give the configuration of your chproxy & the setup of your Redis? Because we're using the cache on redis (+ multiple users of chproxy) and it's the first time we see the issue you mentioned.

[edit]: I looked a the description of the PR (and not just the code) and I understand a bit more. See my comments in the PR.

**Comment by mga-chka** [comment]
I'm closing the issue since the PR fixing it is merge.
It will be in the next release that should be available before the end of the month
