### ISSUE TITLE
[QUESTION] why create a new `reverseProxy`

### ISSUE THREAD

**Issue by ardenwick** [ContentSquare/chproxy#352]
Just out of curiosity, I am learning the code.

As the comment in code says, the code creates a new `reverseProxy` if any settings changed that is used in proxy initialization.

https://github.com/ContentSquare/chproxy/blob/3b8f80ed7a56a6a8f2f59d3be15f92b609f26a2e/main.go#L269-L282

but why is it ? variables like `http.Transport.MaxIdleConns` are only read by `http.ReverseProxy` and only written by chproxy, can we just apply these settings on `http.Transport` ?

like :

```go

t := rp.rp.Transport.(*http.Transport)
cfg := cfg.ConnectionPool

t.MaxIdleConns = cfg.MaxIdleConns
t.MaxIdleConnsPerHost = cfg.MaxIdleConnsPerHost
t.MaxConnsPerHost = cfg.MaxConnsPerHost

```

**Comment by ardenwick** [comment]
what happens to the old `proxy` and all Timers/Tickers in it, will it be a memory leak ?

**Comment by ardenwick** [comment]
the Timers/Tickers in old `proxy` will not be garbage-collected, as per 

- [How Do They Do It: Timers in Go](https://blog.gopheracademy.com/advent-2016/go-timers/), and 
- [Do I need to explicitly stop a ticker whose reference has been reassigned?](https://stackoverflow.com/questions/40600569/do-i-need-to-explicitly-stop-a-ticker-whose-reference-has-been-reassigned)

says, timer variables should be explicitly `Stop`ed.

**Comment by Blokje5** [comment]
@cangyin A lot of the code base is old and the original maintainers no longer work on the project (we took over maintainance of the project about 1/2 years ago). The code base for example was written pre-context (e.g. you see done channels being used instead of just passing a `context` to a method. 

However, we have to be careful with refactoring, as we don't have complete test coverage and we might introduce subtle bugs and performance regressions. Especially with regards to performance, we don't have easily repeatable benchmarks yet  as part of this project.

**Comment by ardenwick** [comment]
See. Thanks for you reply!
