### ISSUE TITLE
multiple responds

### ISSUE THREAD

**Issue by ardenwick** [ContentSquare/chproxy#353]
code here may write 2 responses to client

https://github.com/ContentSquare/chproxy/blob/3b8f80ed7a56a6a8f2f59d3be15f92b609f26a2e/proxy.go#L464-L468

**Comment by ardenwick** [comment]
if query is not cached, and http.StatusBadGateway is returned from `httputil.ReverseProxy`, then this code logic writes multiple responses to client:

```go
reverseProxy.ServeHTTP()
reverseProxy.proxyRequest()

rp.rp.ServeHTTP(rw, req)

if rw.StatusCode() == http.StatusBadGateway {
    // ...
    respondWith(srw, err, srw.StatusCode())
}
```

**Comment by Blokje5** [comment]
@cangyin good catch. Feel free to create a PR (with a test case) to fix this behaviour. If you need any help, feel free to ask 😄 .

**Comment by mga-chka** [comment]
The code is a bit misleading.
When the cache is activated and CH responses with a bad gateway:
* there is first a call to `respondWith` here https://github.com/ContentSquare/chproxy/blob/master/proxy.go#L269
* then there is a call to `RespondWithData` here https://github.com/ContentSquare/chproxy/blob/master/proxy.go#L472

`RespondWithData` writes the header and the content of the msg while `respondWith` only writes the header.
So, `WriteHeader` will be called twice (which is not an issue) and the content of the error msg only once.

Since the call to `respondWith` is needed when the cache is not activated, I won't change the code (but add a few tests to be sure this part is covered if someone does a refactoring in the future)
