### ISSUE TITLE
CHProxy caching(v1.24.0)

### ISSUE THREAD

**Issue by tjthink** [ContentSquare/chproxy#358]
set cache expired 1second, but Clean every minute. Even after clearing the cache, it can still hit the cache. please help me.
![image](https://github.com/ContentSquare/chproxy/assets/5283107/4ea7310a-5026-443f-a5f5-2ff8a09377b4)
![image](https://github.com/ContentSquare/chproxy/assets/5283107/04719951-45f2-4be8-9b32-ac2ad3fc665f)

![190NMRE83I_OSF_1T_FW1IT](https://github.com/ContentSquare/chproxy/assets/5283107/32b03718-44d2-40bd-87cd-add1e509247b)
![image](https://github.com/ContentSquare/chproxy/assets/5283107/3bf9f969-e11d-40a7-9395-f8dda1a011af)

**Comment by mga-chka** [comment]
Hi,can you copy paste the full config file (feel free to anynomize sensitive parts) so that we can reproduce the issue on our side?

**Comment by mga-chka** [comment]
no need for the full config. I looked at the code and indeed, the filesystem cache has weird limitations: the TTL must be above 1 minute & below 1 hour:
https://github.com/ContentSquare/chproxy/blob/master/cache/filesystem_cache.go#L202
I'll see with the dev who made this change if it was intentional or if there is a bug

**Comment by mga-chka** [comment]
I took at look at the code and for the filesystem cache, the data are cleaned at best every minute (up to every hour depending on the expire variable).
You're hitting the cache because in order to know if a data is still "fresh" we don't only use the expire duration but  both the expire + grace durations.
cf https://github.com/ContentSquare/chproxy/blob/master/cache/filesystem_cache.go#L109

So, you should put the grace_time to 0 in the cache config

**Comment by tjthink** [comment]
Thank you, I will try what you suggested.

**Comment by mga-chka** [comment]
@tjthink did you apply the change? If yes, did it solve the issue?
