### ISSUE TITLE
Allowed or Disallowed Query List (Words) Feature

### ISSUE THREAD

**Issue by alivelimeli** [ContentSquare/chproxy#7]
Hello,

I think it will be nice if you can some settings to allow only specific queries or deny specific queries (or maybe both).

For example:

allowed_query_words = SELECT,USE,SHOW,DESCRIBE,EXISTS,USE,KILL
disallowed_query_words=CREATE,ALTER,DROP,INSERT

So the user will only able to send queries starting with "SELECT"

I know there is a readonly mechanism inside Clickhouse. But through proxy we can restrict proxy users more granular.

What do you think?

**Comment by valyala** [comment]
Currently `chproxy` doesn't parse the incoming query at all - it just proxies it as-is to `clickhouse`. The requested feature would require adding non-trivial query parser into `chproxy`. There is a hacky solution - just scan the first word of the query and determine whether it is allowed. It is already used when determining whether to cache the response - see [canCacheQuery](https://github.com/Vertamedia/chproxy/blob/16e9349dd37e88d59d37e5696ef672992f6388cf/utils.go#L140). Such hacky solution may fail when the query starts with unexpected syntax, for instance with a `-- comment` or `WITH` statement. So the solution may break at any time.

As you already mentioned, `clickhouse` already provides [readonly](http://clickhouse-docs.readthedocs.io/en/latest/access_rights.html) mechanism for disabling non-readonly queries, thus lowering the importance of the feature.

@alivelimeli , could your provide use cases for this feature?

**Comment by alivelimeli** [comment]
Yes its possible to make a hacky solution like that. I've thought that maybe chproxy can be behaves like a WAF (Web Application Firewall) to limit some kind of queries. Thanks

**Comment by valyala** [comment]
From security POV it would be better to implement only `allowed_query_prefixes`, because `disallowed_query_prefixes` can be easily misconfigured.

But even the simplest `allowed_query_prefixes: SELECT` gives false sense of security, since:
* `SELECT` query may be specially crafted the way that exhausts all the available RAM or CPU resources;
* `SELECT` syntax may be extended in the future in unsafe ways allowing writing output files on the server side, creating new tables or doing other nasty things;
* `ClickHouse` may contain security bugs that may be easily triggered via specially crafted `SELECT` queries.

It is bad practice from security POV to allow untrusted direct `SELECT` access to any DBMS, not only `ClickHouse`. So even `allowed_query_prefixes` has little sense :(
